name: pages-build-deployment

on:
  push:
    branches: ["web-page"]
    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Pull ghcr.io/actions/jekyll-build-pages:v1.0.13
        uses: actions/jekyll-build-pages@v1

      - name: Checkout
        uses: actions/checkout@v7

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: "./docs"
          destination: "./docs/_site"
          verbose: true
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './docs/_site'
          retention-days: 1
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
